// Generated by delombok at Wed Jan 13 22:27:29 EST 2021
package net.md_5.bungee.api.chat;

import net.md_5.bungee.api.chat.ClickEvent.Action;

public final class ClickEvent {
    /**
     * The type of action to perform on click
     */
    private final Action action;
    /**
     * Depends on action
     *
     * @see Action
     */
    private final String value;


    public enum Action {
        /**
         * Open a url at the path given by
         * {@link net.md_5.bungee.api.chat.ClickEvent#value}
         */
        OPEN_URL, 
        /**
         * Open a file at the path given by
         * {@link net.md_5.bungee.api.chat.ClickEvent#value}
         */
        OPEN_FILE, 
        /**
         * Run the command given by
         * {@link net.md_5.bungee.api.chat.ClickEvent#value}
         */
        RUN_COMMAND, 
        /**
         * Inserts the string given by
         * {@link net.md_5.bungee.api.chat.ClickEvent#value} into the players
         * text box
         */
        SUGGEST_COMMAND, 
        /**
         * Change to the page number given by
         * {@link net.md_5.bungee.api.chat.ClickEvent#value} in a book
         */
        CHANGE_PAGE;
    }

    /**
     * The type of action to perform on click
     */
    @java.lang.SuppressWarnings("all")
    public Action getAction() {
        return this.action;
    }

    /**
     * Depends on action
     *
     * @see Action
     */
    @java.lang.SuppressWarnings("all")
    public String getValue() {
        return this.value;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ClickEvent(action=" + this.getAction() + ", value=" + this.getValue() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public ClickEvent(final Action action, final String value) {
        this.action = action;
        this.value = value;
    }
}
