// Generated by delombok at Wed Jan 13 22:27:29 EST 2021
package net.md_5.bungee.api.chat;

public final class HoverEvent {
    private final Action action;
    private final BaseComponent[] value;


    public enum Action {
        SHOW_TEXT, SHOW_ACHIEVEMENT, SHOW_ITEM, SHOW_ENTITY;
    }

    @java.lang.SuppressWarnings("all")
    public Action getAction() {
        return this.action;
    }

    @java.lang.SuppressWarnings("all")
    public BaseComponent[] getValue() {
        return this.value;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "HoverEvent(action=" + this.getAction() + ", value=" + java.util.Arrays.deepToString(this.getValue()) + ")";
    }

    @java.lang.SuppressWarnings("all")
    public HoverEvent(final Action action, final BaseComponent[] value) {
        this.action = action;
        this.value = value;
    }
}
